### ISSUE TITLE
Startup parameter not working

### ISSUE THREAD

**Issue by DrNuenninger** [alexwiese/LiveLogViewer#12]
When I start the program with a specified log file to monitor, it prompts me to select a logfile anyway.
This is either a bug or I'm doing something wrong, in which case more documentation on the parameter usage would be very nice.

These are my shortcut settings: 
"E:\LiveLogViewer\Live Log Viewer.exe" [...Long Path]\Papyrus.0.log
I also tried opening it directly using a console.

Loving the Viewer so far though 👍

**Comment by alexwiese** [comment]
@SirMossi any ideas on this one?

**Comment by alexwiese** [comment]
@DrNuenninger  Looks like the latest release didn't happen and you're using an older version.
I've kicked off a build now. Once 4.0.3 is ready please try that out

**Comment by alexwiese** [comment]
Release [4.0.3](https://github.com/alexwiese/LiveLogViewer/releases/tag/4.0.3) is now available

**Comment by SirMossi** [comment]
Also make sure to put the log filename in quotation marks, if it contains spaces (standard windows behaviour)

**Comment by DrNuenninger** [comment]
Works like a charm now thanks :). Just as a note, chrome flagged the download as "unusual and potentially malicious" which might be because of the pdb file you left in the zip.
