### ISSUE TITLE
Error: The settings property 'DefaultEncoding' was not found.

### ISSUE THREAD

**Issue by nex86** [alexwiese/LiveLogViewer#16]
---------------------------
Error
---------------------------
Error: The settings property 'DefaultEncoding' was not found.
---------------------------
OK   
---------------------------

getting this error when opening the log file.
how to fix that?

**Comment by mBednarz92** [comment]
Did you manage to fix that? Facing same issue

**Comment by alexwiese** [comment]
@mBednarz92  using .NET 5.0 or 4.5 version?

**Comment by alexwiese** [comment]
@mBednarz92 try grabbing the latest release [here](https://github.com/alexwiese/LiveLogViewer/releases/tag/4.0.4) - I've updated it
